pipeline {
    agent any
    stages {
        stage('Clone Repo') {
            steps {
                sh "git clone https://github.com/Bantoki-san/simple-java-maven-app.git"
            }
        }
        stage('Build') {
            steps {
                sh "sed -i 's/3.8.6/3.6.3/g' pom.xml"
                sh "mvn clean install"
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
